name = "realtime-clipboard"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[durable_objects.bindings]]
name = "CLIPBOARD"
class_name = "ClipboardDurable"
script_name = "realtime-clipboard"

[[migrations]]
tag = "v1"
new_classes = ["ClipboardDurable"]
